### ISSUE TITLE
Generate new site section and article options doesn't work

### ISSUE THREAD

**Issue by Appmeurtre** [nunocoracao/blowfish-tools#53]
Like in the title I said, when I click generate either article or site section, tool says it is generated but no changes made to actual site.

Windows 10 21H2 ver.19044

**Comment by nunocoracao** [comment]
Thanks @Appmeurtre can you provide more context on your setup. Please include OS as I suspect I know what is going on...

**Comment by Appmeurtre** [comment]
> Thanks @Appmeurtre can you provide more context on your setup. Please include OS as I suspect I know what is going on...

RTX 3070M
i7-12700H
16 GB RAM
Windows 10 LTSC 21H2 "with all updates downloaded" (OS Build 19044.3930)

Installed using npm, tried with Powershell 5.1 and 7.1; also cmd both with or without admin privileges,
using; 
Windows Terminal > 1.19.3172.0
Node JS version > 21.6.0
GO version > 1.21.6
Hugo version > 0.122.0

In first I thought maybe windows defender was doing something so I also disabled it via group policy, no luck.

**Comment by nunocoracao** [comment]
@Appmeurtre I think this is my bad I might be shooting commands to the system just covering unix. Could you try with WSL and let me know if it works? I want to fix this for powershell but I might need more time to convert the commands for that use-case and make sure I test both OSes.

**Comment by Appmeurtre** [comment]
> @Appmeurtre I think this is my bad I might be shooting commands to the system just covering unix. Could you try with WSL and let me know if it works? I want to fix this for powershell but I might need more time to convert the commands for that use-case and make sure I test both OSes.

It is working with WSL Debian 12. No problem at all. I guess I will just edit with vsc for now.

**Comment by nunocoracao** [comment]
@Appmeurtre issuing commands via shell didn't think about powershell

**Comment by nunocoracao** [comment]
@Appmeurtre after some research adding support for powershell it's not feasible for me (lack of time and resources). I've added a warning for windows users to consider using WSL if they are running the tool in Powershell.
