### ISSUE TITLE
Running blowfish-tools to create new site modifying results in  ./config/_default/languages.en.toml does not exist

### ISSUE THREAD

**Issue by crluehmann** [nunocoracao/blowfish-tools#60]
I'm new with Hugo and blowfish, but it seems when using 'npx blowfish-tools' to create a new site, when you try to modify it, the modification fails saying the ./config/_defaults/ related file does not exist.

I'm using 'npx blowfish-tools' in a new directory and the install solely comes from blowfish-tools.  I have tried on PowerShell (not Windows PowerShell) and WSL with similar results.

Is there something I'm missing?

**Comment by crluehmann** [comment]
Yes, I created the site using npx blowfish-tools, then CDed into the directory.

I then used the option to modify the site title.  Then blowfish-tools threw an error saying that ./config/_defaults/language.en.toml does not exist.

I can update in a few minutes with exact commands and responses.

**Comment by crluehmann** [comment]
in PowerShell on Win 11 23H2, hugo v0.124.1 extended.

Commands & response:
npx blowfish-tools
Setup a new website with Blowfish - entered name, installed
Selected Configure overall site
Selected Site's title
response: File ./config/_default/languages.en.toml does not exist.

**Comment by nunocoracao** [comment]
@crluehmann will need sometime to figure out how I can reproduce/fix this one in my setup - aka I don't have a windows machine. Any ideas if it's possible to emulate a powershell on mac?

**Comment by nunocoracao** [comment]
Will try to debug today

**Comment by nunocoracao** [comment]
should be fixed in 1.4.0

**Comment by crluehmann** [comment]
Thank you!

**Comment by nunocoracao** [comment]
Was it fixed?

**Comment by crluehmann** [comment]
Unfortunately not -- same output:

√ What do you want to configure? Start typing to search for options or scroll down to see all options · Site's title
File ./config/_default/languages.en.toml does not exist.

**Comment by nunocoracao** [comment]
Hmm... is the file there? 
Can you give me a repo so that I can check

**Comment by crluehmann** [comment]
Sure -- empty directories weren't synced, but I ran blowfish-tools then created a repo with the folder

https://github.com/crluehmann/testing-blowfish

**Comment by nunocoracao** [comment]
Ok so files were not created... this doesn't happen in my case with powershell on mac... need a win machine to debug this.

**Comment by nunocoracao** [comment]
Released fix in https://github.com/nunocoracao/blowfish-tools/releases/tag/v1.5.0
Let me know if it works @crluehmann

**Comment by crluehmann** [comment]
@nunocoracao - It does work!!  Thank you so much!!
