### ISSUE TITLE
Add option for initializing a project with exampleSite content

### ISSUE THREAD

**Issue by pwab** [nunocoracao/blowfish-tools#62]
Maybe I overlooked it but an option for copying the exampleSite's content into a freshly created hugo-blowfish-project would be nice. So something like: `Create a new site? -> Yes -> Would you like to add example content? -> Yes` would lead to copy and paste of the exampleSite folder from the blowfish repository into my created local hugo project.

This would make it easier to just install the blowfish-tools, run the project init process and then get a working instance of the example-site locally. Right now it is a manual two step process (create the initial site template and then copy-paste the content).

By the way: Great tool for a nice hugo theme!

**Comment by nunocoracao** [comment]
I have a different idea :) hold my beer

**Comment by nunocoracao** [comment]
@pwab added option to start from one of several templates
