### ISSUE TITLE
Can't create a section or new post on Windows

### ISSUE THREAD

**Issue by schellingerhout** [nunocoracao/blowfish-tools#72]
I am unable to create a section or new post on Windows using the client. I tried on command prompt, powershell and Git Bash. I also noticed that dragging and dropping files to the shell causes quirks with the different ways that that the shells respond to paths especially paths with spaces in them.

Addressed by #71

**Comment by nunocoracao** [comment]
Hello @schellingerhout closing this since i t was fixed of https://github.com/nunocoracao/blowfish-tools/pull/71
