### ISSUE TITLE
Module "Blowfish" Not compatible.

### ISSUE THREAD

**Issue by tetricky** [nunocoracao/blowfish-tools#75]
I had a container image, which I was using to develop a site. Blowfish tools appeared to be working, and I could edit items and when I was editing items I could preview them.

I updated blowfish, using the option `Update Blowfish installation` and this appeared to no longer be the case. I can't be sure of the exact history, because I was editing items as normal...and leaving and coming back to it over a period of a few weeks. What I hadn't done in this period was update the container tools.

Attempting to `Generate the static site with Hugo` or `Run a local server with Blowfish` doesn't work.

In `Generate the static site with Hugo` I get the following errors....although confusingly static site files are generated in the public directory (I don't currently have a mechanism to see if they are correct, and the site is not built yet, so they wont be).

```
WARN  Module "blowfish" is not compatible with this Hugo version: 0.87.0/0.128.2; run "hugo mod graph" for more information.
Start building sites … 
hugo v0.131.0-bfbee17932ff24009008aa94cdd75c0c41f59279 linux/amd64 BuildDate=2024-08-02T09:03:48Z VendorInfo=gohugoio

ERROR Failed to publish Resource: open /src/my_site-blowfish/public: is a directory
Total in 231 ms
Error: error building site: logged 1 error(s)
my_site:/src/my_site-blowfish# ls -la public/
total 1328
drwxr-xr-x    9 root     root          4096 Aug  8 11:08 .
drwxr-xr-x   13 root     root          4096 Jun 24 14:47 ..
-rw-r--r--    1 root     root         14004 Aug  8 11:08 404.html
-rw-r--r--    1 root     root         17874 Jun 24 10:41 android-chrome-192x192.png
-rw-r--r--    1 root     root         37648 Jun 24 10:41 android-chrome-512x512.png
-rw-r--r--    1 root     root         16152 Jun 24 10:41 apple-touch-icon.png
drwxr-xr-x    2 root     root          4096 Aug  8 11:08 authors
drwxr-xr-x    2 root     root          4096 Aug  8 11:08 categories
drwxr-xr-x    2 root     root          4096 Aug  8 11:08 css
-rw-r--r--    1 root     root           737 Jun 24 10:41 favicon-16x16.png
-rw-r--r--    1 root     root          1823 Jun 24 10:41 favicon-32x32.png
-rw-r--r--    1 root     root         15406 Jun 24 10:41 favicon.ico
-rw-r--r--    1 root     root        711077 Aug  8 11:08 home-background.jpg
-rw-r--r--    1 root     root         15924 Aug  8 11:08 index.html
-rw-r--r--    1 root     root           627 Aug  8 11:08 index.json
-rw-r--r--    1 root     root           483 Aug  8 11:08 index.xml
drwxr-xr-x    2 root     root          4096 Aug  8 11:08 js
drwxr-xr-x    3 root     root          4096 Aug  8 11:08 lib
-rw-r--r--    1 root     root        450977 Aug  8 11:08 my_site-logo.png
-rw-r--r--    1 root     root            67 Aug  8 11:08 robots.txt
drwxr-xr-x    2 root     root          4096 Aug  8 11:08 series
-rw-r--r--    1 root     root           263 Jun 24 10:41 site.webmanifest
-rw-r--r--    1 root     root           290 Aug  8 11:08 sitemap.xml
drwxr-xr-x    2 root     root          4096 Aug  8 11:08 tags
my_site:/src/my_site-blowfish# 
```

`Hugo version: 0.87.0/0.128.2` is likely the hugo version of the container that `my_site` was originally built under. I have updated the container image to the latest hugo ( floryn90/hugo:0.131.0-pandoc ) and installed the latest blowfish-tools and that's now what I get. The same behaviour as in the original container after I  updated blowfish from the blowfish-tools menu.

This is a broken state for me...I have looked on blowfish, and blowfish tools github and not really found an indication of required, unsupported versions of hugo....or whatever other dependencies might be problematic. I'm stumped.

I would like to create a working container, that allows preview, and will build a static site without error. It doesn't particularly need to be specific functionality. I would just like to take a blowfish-tool project from cradle to grave, to see it working. I am expecting that mid-project upgrading will be off the agenda to achieve this.

I did have a working system. Now I don't. My best guess is that it was updating the blowfish them that caused this. What can I do to advance or trouble shoot this?

**Comment by tetricky** [comment]
I think we can certainly write some of this off to my error. I noticed the version mismatch, and reverted my container back to hugo v0.128.2. I must have updated and not realised I'd lost the preview and generate.

Now most of the errors are gone. What I still can't seem to do is generate static sites or preview.

```
Start building sites … 
hugo v0.128.2-de36c1a95d28595d8243fd8b891665b069ed0850 linux/amd64 BuildDate=2024-07-04T08:13:25Z VendorInfo=gohugoio

ERROR Failed to publish Resource: open /src/my_site-blowfish/public: is a directory
Total in 199 ms
Error: error building site: logged 1 error(s)
```

I'm broadly stuck. I don't understand how to resolve the error...and I think everything is back to the versions it was previously when it was working.

Initialising a new site gets me back to a working installation. Does this mean my clumsy haphazard upgrading has fundamentally broken what I've done, and I need to start again? or might it be retrievable?

**Comment by nunocoracao** [comment]
It is retrievable. Please open a new discussion (not an issue) in the blowfish repo.

**Comment by tetricky** [comment]
My apologies. I should have closed this. I don't have this any more - I rebuilt the site on a stable platform. Thank you for your work.
